version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    container_name: dmc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dmc
      POSTGRES_PASSWORD: dmc
      POSTGRES_DB: dmc
    ports:
      - '5432:5432'
    volumes:
      - dmc_pgdata:/var/lib/postgresql/data
volumes:
  dmc_pgdata:



